### PR TITLE
Swift 4 Upgrades + Travis CI Integration

### PR DESCRIPTION
**Pull request by harens**
RootsEncoder, gRPC.framework, gRPCTests.xctest and zlib-example converted to Swift 4. A .travis.yml has been written and tested, whilst some of the documentation has been corrected.

### CODE REVIEW

**Comment by vanshg** [comment]
Hey @harens, thank you for the pull request! I've just pushed an update that begins a revamp of the project. With it, I've upgraded to Swift 4 and essentially started from scratch for the new project. Can you take a verify that the Travis CI would still work and update the PR?

**Comment by harens** [comment]
Thanks @vanshg for your response. I would be more than happy to check if Travis CI would still work, though I'll send it as a separate PR.

**Comment by vanshg** [comment]
Awesome thanks @harens!

**Comment by harens** [comment]
@vanshg I am having some trouble building the project. I was wondering how you've built it with the updated submodules?

**Pull request closed without merging**
