### PR TITLE
Update to Xcode 10.2.1 (pods, proj metadata and Swift)

### PR DESCRIPTION
**Pull request by karol-depka**

### CODE REVIEW

**Comment by vanshg** [comment]
Hi @karol-depka, thanks for the contribution! Looks like the CI is failing and I think it's because of Xcode version that Azure is using to build. (see: https://github.com/Microsoft/azure-pipelines-image-generation/tree/master/images/macos). Could you also update the `azure-ci.yml` file from `vmImage: 'macOS 10.13'` to `vmImage: 'macOS 10.14'`. That will use Xcode 10.2.1 by default, which is what you have compiled with. I think then the CI will pass, and I can get this merged.

**Comment by vanshg** [comment]
LGTM!

**Comment by karol-depka** [comment]
Cool. Thanks :).
Any way/plans to allow the assistant "to use a screen" ?

**Comment by vanshg** [comment]
What do you mean by use a screen?

**Comment by longnd** [comment]
chalk-google-smart-assistants-ga00516-us-64_1000
I guess that means to visualize the response - like what Google home hub does.
But I don't think it's possible.

**Comment by vanshg** [comment]
There is an `htmlOut` field returned by the Assistant API so it might be possible

**Pull request merged**
